name: Update README with report links

on:
  push:
    paths:
      - reports/*.md  # Triggered by new or modified report files
  workflow_dispatch:  # Allows manual trigger via GitHub Actions UI

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find all .md files in the reports directory and sort by date
        run: |
          # Find all .md files and sort them by modification date (newest first)
          report_files=$(find reports -type f -name "*.md" | sort -r)

          if [ -z "$report_files" ]; then
            echo "No report files found."
            exit 1  # Exit if no reports are found
          fi

          # Format the list of files and set it as an environment variable
          REPORT_FILES=$(echo "$report_files" | tr '\n' ' ')  # Join file paths with spaces

          echo "REPORT_FILES=$REPORT_FILES" >> $GITHUB_ENV  # Set environment variable
          
      - name: Update README with report links
        run: |
          # Create or update the README with links to the reports
          echo "## Weekly Reports" > README.md
          for report in $REPORT_FILES; do
            echo "- [$(basename "$report")](./$report)" >> README.md
          done
          
          # Commit the updated README file
          git add README.md
          git commit -m "Update README with report links"
          git push
