name: Update README with new report links

on:
  workflow_run:
    workflows: ["GitHub Contributions Report"]
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find the latest report file
        id: find_report
        run: |
          # Find the most recent report file in the /reports directory
          report_file=$(find reports -type f -name "*.md" -printf "%T+ %p\n" | sort -r | head -n 1 | cut -d' ' -f2)
          echo "REPORT_FILE=$report_file" >> $GITHUB_ENV

      - name: Update README with the new report link
        run: |
          # Always update the README with the new report link
          if [ -z "$REPORT_FILE" ]; then
            echo "No new report file found."
            exit 1  # Exit if no report is found, but still run the update process
          fi
          
          # Check if the link to the report already exists in README.md, then remove it
          sed -i '/## Latest Contribution Report/d' README.md
          sed -i '/You can find the latest contribution report/d' README.md
          
          # Append the new link to the README.md file
          echo "## Latest Contribution Report" >> README.md
          echo "You can find the latest contribution report [here](./$REPORT_FILE)." >> README.md

          # Stage the README.md file for commit
          git add README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Commit the changes to README.md
          git commit -m "Update README with new report link" || echo "No changes to commit"
          
          # Push the changes back to the main branch
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
